services:
  - type: web
    name: edusphere-api
    runtime: python
    env: production
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port ${PORT}"
    envVars:
      - key: SUPABASE_URL
        fromSecret: SUPABASE_URL
      - key: SUPABASE_SERVICE_ROLE_KEY
        fromSecret: SUPABASE_SERVICE_ROLE_KEY
    secrets:
      - SUPABASE_URL
      - SUPABASE_SERVICE_ROLE_KEY
